#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xB3C7CE210DE76DFC (tingping@fedoraproject.org)
#
Name     : hexchat
Version  : 2.14.2
Release  : 25
URL      : https://dl.hexchat.net/hexchat/hexchat-2.14.2.tar.xz
Source0  : https://dl.hexchat.net/hexchat/hexchat-2.14.2.tar.xz
Source99 : https://dl.hexchat.net/hexchat/hexchat-2.14.2.tar.xz.asc
Summary  : Header and path for HexChat plugins
Group    : Development/Tools
License  : GPL-2.0 MIT
Requires: hexchat-bin
Requires: hexchat-lib
Requires: hexchat-data
Requires: hexchat-license
Requires: hexchat-locales
Requires: hexchat-man
BuildRequires : appstream-glib
BuildRequires : buildreq-meson
BuildRequires : dbus-dev
BuildRequires : desktop-file-utils
BuildRequires : gdk-pixbuf
BuildRequires : gdk-pixbuf-dev
BuildRequires : gtk+-dev
BuildRequires : intltool
BuildRequires : libnotify-dev
BuildRequires : lua-dev
BuildRequires : openssl-dev
BuildRequires : pkgconfig(dbus-glib-1)
BuildRequires : pkgconfig(libcanberra)
BuildRequires : pkgconfig(libproxy-1.0)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : python3-dev

%description
# HexChat [![Build Status](http://img.shields.io/travis/hexchat/hexchat/master.svg?style=flat)](https://travis-ci.org/hexchat/hexchat) [![Build Status](https://img.shields.io/appveyor/ci/TingPing/hexchat/master.svg?style=flat)](https://ci.appveyor.com/project/TingPing/hexchat)

%package bin
Summary: bin components for the hexchat package.
Group: Binaries
Requires: hexchat-data
Requires: hexchat-license
Requires: hexchat-man

%description bin
bin components for the hexchat package.


%package data
Summary: data components for the hexchat package.
Group: Data

%description data
data components for the hexchat package.


%package dev
Summary: dev components for the hexchat package.
Group: Development
Requires: hexchat-lib
Requires: hexchat-bin
Requires: hexchat-data
Provides: hexchat-devel

%description dev
dev components for the hexchat package.


%package lib
Summary: lib components for the hexchat package.
Group: Libraries
Requires: hexchat-data
Requires: hexchat-license

%description lib
lib components for the hexchat package.


%package license
Summary: license components for the hexchat package.
Group: Default

%description license
license components for the hexchat package.


%package locales
Summary: locales components for the hexchat package.
Group: Default

%description locales
locales components for the hexchat package.


%package man
Summary: man components for the hexchat package.
Group: Default

%description man
man components for the hexchat package.


%prep
%setup -q -n hexchat-2.14.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535643451
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --prefix /usr --buildtype=plain -Dwith-gtk=true -Dwith-ssl=true -Dwith-dbus=true -Dwith-libproxy=true -Dwith-libnotify=true -Dwith-libcanberra=true -Dwith-python=python3 -Dwith-lua=false -Dwith-perl=false  builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/doc/hexchat
cp COPYING %{buildroot}/usr/share/doc/hexchat/COPYING
cp plugins/fishlim/LICENSE %{buildroot}/usr/share/doc/hexchat/plugins_fishlim_LICENSE
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang hexchat

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/hexchat

%files data
%defattr(-,root,root,-)
/usr/share/applications/io.github.Hexchat.desktop
/usr/share/dbus-1/services/org.hexchat.service.service
/usr/share/icons/hicolor/48x48/apps/hexchat.png
/usr/share/icons/hicolor/scalable/apps/hexchat.svg
/usr/share/metainfo/io.github.Hexchat.appdata.xml

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/pkgconfig/hexchat-plugin.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/hexchat/plugins/checksum.so
/usr/lib64/hexchat/plugins/fishlim.so
/usr/lib64/hexchat/plugins/python.so
/usr/lib64/hexchat/plugins/sysinfo.so

%files license
%defattr(-,root,root,-)
/usr/share/doc/hexchat/COPYING
/usr/share/doc/hexchat/plugins_fishlim_LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/hexchat.1

%files locales -f hexchat.lang
%defattr(-,root,root,-)

