#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : hexchat
Version  : 2.12.2
Release  : 9
URL      : https://dl.hexchat.net/hexchat/hexchat-2.12.2.tar.xz
Source0  : https://dl.hexchat.net/hexchat/hexchat-2.12.2.tar.xz
Summary  : Header and path for HexChat plugins
Group    : Development/Tools
License  : GPL-2.0 MIT
Requires: hexchat-bin
Requires: hexchat-lib
Requires: hexchat-data
Requires: hexchat-locales
Requires: hexchat-doc
BuildRequires : dbus-dev
BuildRequires : gdk-pixbuf
BuildRequires : gdk-pixbuf-dev
BuildRequires : gettext
BuildRequires : gtk+-dev
BuildRequires : intltool
BuildRequires : libnotify-dev
BuildRequires : lua-dev
BuildRequires : openssl-dev
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(gtk+-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(libpci)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(openssl)
BuildRequires : python-dev
BuildRequires : shared-mime-info
Patch1: 0001-Bump-version-to-2.12.2.patch
Patch2: 0002-Update-translations.patch
Patch3: 0003-Don-t-abort-if-translated-text-event-fails.patch
Patch4: 0004-mpcinfo-Fix-memory-leaks.patch
Patch5: 0005-fishlim-Fix-MEMZERO-macro-using-element-number-not-b.patch
Patch6: 0006-Added-MHOP-command.patch
Patch7: 0007-perl-Remove-dead-assignment.patch

%description
# HexChat [![Build Status](http://img.shields.io/travis/hexchat/hexchat.svg?style=flat)](https://travis-ci.org/hexchat/hexchat) [![Build Status](http://img.shields.io/jenkins/s/http/node1.sored.pl:8090/hexchat.svg?style=flat)](http://node1.sored.pl:8090/job/hexchat/)

%package bin
Summary: bin components for the hexchat package.
Group: Binaries
Requires: hexchat-data

%description bin
bin components for the hexchat package.


%package data
Summary: data components for the hexchat package.
Group: Data

%description data
data components for the hexchat package.


%package dev
Summary: dev components for the hexchat package.
Group: Development
Requires: hexchat-lib
Requires: hexchat-bin
Requires: hexchat-data
Provides: hexchat-devel

%description dev
dev components for the hexchat package.


%package doc
Summary: doc components for the hexchat package.
Group: Documentation

%description doc
doc components for the hexchat package.


%package lib
Summary: lib components for the hexchat package.
Group: Libraries
Requires: hexchat-data

%description lib
lib components for the hexchat package.


%package locales
Summary: locales components for the hexchat package.
Group: Default

%description locales
locales components for the hexchat package.


%prep
%setup -q -n hexchat-2.12.2
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1
%patch7 -p1

%build
export LANG=C
%configure --disable-static --disable-lua
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install
%find_lang hexchat

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/hexchat

%files data
%defattr(-,root,root,-)
/usr/share/appdata/hexchat.appdata.xml
/usr/share/applications/hexchat.desktop
/usr/share/icons/hicolor/48x48/apps/hexchat.png
/usr/share/icons/hicolor/scalable/apps/hexchat.svg

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/hexchat/plugins/checksum.so
/usr/lib64/hexchat/plugins/doat.so
/usr/lib64/hexchat/plugins/fishlim.so
/usr/lib64/hexchat/plugins/perl.so
/usr/lib64/hexchat/plugins/python.so
/usr/lib64/hexchat/plugins/sysinfo.so

%files locales -f hexchat.lang 
%defattr(-,root,root,-)

